filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/scrape_logs/*

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"
